### ISSUE TITLE
Having trouble running this.

### ISSUE THREAD

**Issue by michaelsboost** [fkrauthan/SimpleTwitter#1]
I followed your documentation listen [here](https://github.com/fkrauthan/SimpleTwitter/blob/master/README.md) and have all the packages/dependencies installed along with MongoDB. 

I'm trying to run this via localhost but my terminal gives me ....
![screen shot 2016-08-26 at 12 53 26 pm](https://cloud.githubusercontent.com/assets/2473707/18015240/6835a5d2-6b8c-11e6-8789-baafaf261c38.png)

If you can help it'd be greatly appreciated.

**Comment by fkrauthan** [comment]
You could just run it via `node ./server/bin/server`. Or change the first line of the file ./server/bin/server to `#!/usr/bin/env node`

**Comment by michaelsboost** [comment]
lol ok now it's running

Is this normal with SimpleTwitter?
![screen shot 2016-08-26 at 2 36 33 pm](https://cloud.githubusercontent.com/assets/2473707/18018082/8c315c16-6b9a-11e6-8629-1579a3421bd1.png)

**Comment by fkrauthan** [comment]
This indicates that the website is still submitting the request (the API server hasn't responded yet that the message was received). This should go away. If not take a look at the Developer Console to see if there was an API error.

**Comment by michaelsboost** [comment]
lol I figured it out. I noticed private messaging hasn't been added yet
